name: Tests

on: 
  push: 
    branches: 
      - "home-page"
  pull_request:
    branches: 
      - "home-page"

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-vesion }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installation
        run: npm install
      - name: Jest Unit Tests
        run: npm test
